import { Vite } from '../lib/vite/_namespace.js'
import { Build } from './build.js'
import { Path } from '../lib/path/_namespace.js'

export const VitePlugin = (): Vite.PluginOption[] => {
  const entryClientPath = Path.join(import.meta.dirname, `../app-template/entry.client.jsx`)
  const entryServerPath = Path.join(import.meta.dirname, `../app-template/entry.server.jsx`)

  return [
    {
      name: `pollen-build-client`,
      apply: `build`,
      applyToEnvironment: Vite.isEnvironmentClient,
      // HACK: For some reason the ?url import doesn't lead to a rewrite in the build.
      // Furthermore we need to rely on the manifest to get its final name because it is
      // generated by the client build before the server build.
      // However, we still need the asset in development.
      // But we cannot exclude the import in build.
      // So this does that for us but it is really hacky.
      // FIXME
      // 1. Raise issue about having ?url lead to expected build path rewrite?
      // 2. And: Move asset generation to server build?
      // 3. And/or: Use Vite Environments API?
      // generateBundle(_, bundle, isWrite) {
      //   if (isWrite) {
      //     for (const chunkOrAsset of Object.values(bundle)) {
      //       if (chunkOrAsset.type === `asset` && chunkOrAsset.names.includes(`entry.client.jsx`)) {
      //         // eslint-disable-next-line
      //         delete bundle[chunkOrAsset.fileName]
      //       }
      //     }
      //   }
      // },
      config() {
        return {
          environments: {
            client: {
              build: {
                minify: false,
                manifest: true,
                rollupOptions: {
                  input: [entryClientPath],
                },
              },
            },
          },
        }
      },
    },
    Build({
      entryServerPath: entryServerPath,
    }),
  ]
}
