packages:
  - examples/*
  - website
onlyBuiltDependencies:
  - dprint
  - '@playwright/browser-chromium'
  - lightningcss
overrides:
  kit: link:../../../Library/pnpm/global/5/node_modules/@wollybeard/kit
