name: "Run Step"
description: "Run a TypeScript workflow step from .github/steps/<name>.ts"
inputs:
  name:
    description: "The name of the workflow step"
    required: true
  workflow:
    description: "The workflow name for step discovery (defaults to github.workflow)"
    required: false
    default: ""
  inputs:
    description: "JSON string of inputs for the step"
    required: false
    default: "{}"
  context:
    description: "GitHub context object (usually toJSON(github))"
    required: false
    default: "{}"
  previous:
    description: "Outputs from previous steps (e.g. toJSON(steps.previous.outputs))"
    required: false
    default: "{}"
  github_token:
    description: "GitHub token for API access"
    required: false
runs:
  using: "composite"
  steps:
    - name: Run workflow step
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        STEP_INPUTS: ${{ inputs.inputs }}
        STEP_CONTEXT: ${{ inputs.context }}
        STEP_PREVIOUS: ${{ inputs.previous }}
      run: |
        # Use explicit workflow name if provided, otherwise fall back to github.workflow
        WORKFLOW_NAME="${{ inputs.workflow }}"
        if [ -z "$WORKFLOW_NAME" ]; then
          WORKFLOW_NAME="${{ github.workflow }}"
        fi
        node --no-warnings --experimental-transform-types ./src/lib/github-actions/run-step-cli.ts ${{ inputs.name }} "$WORKFLOW_NAME" "$STEP_INPUTS" "$STEP_CONTEXT" "$STEP_PREVIOUS"
