name: Use Latest CI
description: Update CI logic from main branch
runs:
  using: composite
  steps:
    - name: Update CI logic from main
      run: |
        # Fetch main branch
        git fetch origin main

        # Checkout latest .github directory from main
        git checkout origin/main -- .github

        # Reset to avoid committing these changes
        git reset HEAD
      shell: bash