name: 'Build Polen'
description: 'Common build steps for Polen: setup, build, and re-install'

inputs:
  install-playwright:
    description: 'Install Playwright browsers after build'
    required: false
    default: 'false'
  skip-setup:
    description: 'Skip the setup step (useful if already done)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setup
      if: inputs.skip-setup != 'true'
      uses: ./.github/actions/setup

    - name: Build Polen
      shell: bash
      run: pnpm build

    - name: Re-install to link workspace packages
      shell: bash
      run: pnpm install

    - name: Install Playwright browsers
      if: inputs.install-playwright == 'true'
      uses: ./.github/actions/install-playwright-binaries