name: Checkout with Latest CI
description: Checkout repository and update to latest CI logic from main branch
inputs:
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
  fetch-depth:
    description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
    required: false
    default: '1'
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: false
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}
        fetch-depth: ${{ inputs.fetch-depth }}
        path: ${{ inputs.path }}

    - name: Update CI logic from main
      run: |
        # Fetch main branch
        git fetch origin main

        # Checkout latest .github directory from main
        git checkout origin/main -- .github

        # Reset to avoid committing these changes
        git reset HEAD
      shell: bash