name: demos

on:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
  build-polen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Polen
        run: pnpm build

      - name: Re-install to link workspace packages
        run: pnpm install

      - name: Upload Polen build
        uses: actions/upload-artifact@v4
        with:
          name: polen-build
          path: |
            build/
            package.json
            pnpm-lock.yaml
            pnpm-workspace.yaml

  build-examples:
    needs: build-polen
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [pokemon]
        # Add more examples here as needed: [pokemon, github, docs]
        # Uncomment when github example is re-enabled:
        # example: [pokemon, github]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Download Polen build
        uses: actions/download-artifact@v4
        with:
          name: polen-build

      - name: Re-install to link workspace packages
        run: pnpm install

      - name: Get commit SHA
        id: sha
        run: echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build example for latest - ${{ matrix.example }}
        run: pnpm --dir examples/${{ matrix.example }} build --base "/polen/latest/${{ matrix.example }}/"
        
      - name: Create latest build artifact
        run: |
          mkdir -p dist-latest-${{ matrix.example }}
          cp -r examples/${{ matrix.example }}/build/* dist-latest-${{ matrix.example }}/

      - name: Build example for commit-specific - ${{ matrix.example }}
        run: pnpm --dir examples/${{ matrix.example }} build --base "/polen/${{ steps.sha.outputs.sha }}/${{ matrix.example }}/"

      - name: Upload latest build
        uses: actions/upload-artifact@v4
        with:
          name: example-latest-${{ matrix.example }}
          path: dist-latest-${{ matrix.example }}/
          
      - name: Upload commit-specific build
        uses: actions/upload-artifact@v4
        with:
          name: example-commit-${{ matrix.example }}
          path: examples/${{ matrix.example }}/build/

  deploy:
    needs: build-examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup
        
      - name: Get commit SHA
        id: sha
        run: echo "sha=${{ github.sha }}" >> $GITHUB_OUTPUT

      - name: Build demos landing page
        run: node ./scripts/build-demos-index.ts --basePath "/polen/" --currentSha "${{ steps.sha.outputs.sha }}"

      - name: Download all example builds
        uses: actions/download-artifact@v4
        with:
          pattern: example-*
          path: example-builds/

      - name: Prepare deployment structure
        run: |
          # Create deployment directory
          mkdir -p gh-pages-deploy
          
          # Copy landing page to root
          cp dist-demos/index.html gh-pages-deploy/index.html
          
          # Process each example
          for example in pokemon; do
            # Create directories
            mkdir -p gh-pages-deploy/latest/$example
            mkdir -p gh-pages-deploy/${{ steps.sha.outputs.sha }}/$example
            mkdir -p gh-pages-deploy/$example
            
            # Copy latest build
            cp -r example-builds/example-latest-$example/* gh-pages-deploy/latest/$example/
            
            # Copy commit-specific build
            cp -r example-builds/example-commit-$example/* gh-pages-deploy/${{ steps.sha.outputs.sha }}/$example/
            
            # Create redirect for direct demo access
            cat > gh-pages-deploy/$example/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <meta http-equiv="refresh" content="0; url=/polen/latest/$example/">
            <script>window.location.replace("/polen/latest/$example/");</script>
          </head>
          <body>
            <p>Redirecting to <a href="/polen/latest/$example/">/latest/$example/</a>...</p>
          </body>
          </html>
          EOF
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages-deploy
          keep_files: true # Keep previous deployments
