name: examples-deploy

on:
  workflow_call:

permissions:
  contents: write
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build Polen
        run: pnpm build

      - name: Re-install to link workspace packages
        run: pnpm install

      - name: Build demos landing page
        run: node ./scripts/build-demos-index.mjs

      - name: Build Pokemon demo
        run: NODE_OPTIONS="--max-old-space-size=6144" pnpm --dir examples/pokemon build

      # GitHub demo disabled - schema too large for efficient SSG
      # - name: Build GitHub demo
      #   run: NODE_OPTIONS="--max-old-space-size=6144" pnpm --dir examples/github build

      - name: Organize demo builds
        run: |
          # dist-demos already created by build-demos-index.mjs
          cp -r ./examples/pokemon/build ./dist-demos/pokemon
          # cp -r ./examples/github/build ./dist-demos/github

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist-demos