name: Deploy Hive Example to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'examples/hive/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/deploy-hive-example.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Polen
        run: pnpm build

      - name: Build Hive example
        run: |
          cd examples/hive
          pnpm build --base /polen/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'examples/hive/build'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4