name: Deploy Website to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build VitePress documentation
        run: |
          cd website
          pnpm install
          pnpm build

      - name: Upload website artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-dist
          path: website/.vitepress/dist

  build-demos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Polen
        run: pnpm build

      - name: Install Hive example dependencies
        run: |
          cd examples/hive
          pnpm install

      - name: Build Hive example
        run: |
          cd examples/hive
          pnpm build --base /polen/demos/hive/

      - name: Upload demos artifact
        uses: actions/upload-artifact@v4
        with:
          name: demos-dist
          path: examples/hive/build

  combine-and-deploy:
    runs-on: ubuntu-latest
    needs: [build-website, build-demos]
    steps:
      - name: Download website artifact
        uses: actions/download-artifact@v4
        with:
          name: website-dist
          path: deploy-dist

      - name: Download demos artifact
        uses: actions/download-artifact@v4
        with:
          name: demos-dist
          path: deploy-dist/demos/hive

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: deploy-dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4